### PR TITLE
Add Vivaldi browser

### PR DESCRIPTION
**Pull request by Cqoicebordel**
Add the browser Vivaldi to the list of possible browser choice.

Might I suggest, after merging this code, to create a new .pot file and submit it for translations ? Even the strings for Edge are not translated.

### CODE REVIEW

**Comment by Cqoicebordel** [comment]
Any news ?

**Comment by Viper007Bond** [comment]
I don't speak for the team responsible for Browse Happy (I only speak for me), but there's a lot of browsers out there and the site isn't meant to be a comprehensive list of every single browser. It's meant to list the most popular browsers and what the latest version of each is.

[According to Wikipedia](https://en.wikipedia.org/wiki/Vivaldi_(web_browser)#Market_share), Vivaldi currently has a 0.02% market share. That's pretty dang small.

**Comment by Cqoicebordel** [comment]
Yes, there are lots of browser out there, and yes, Vivaldi doesn't have (yet) a lot of market share.
But, 1) Vivaldi was created by Jon von Tetzchner, creator of Opera, with a team of 35 persons. It's not a small time browser built by only one dev. 2) Every browser started at some point with having only one (1) user. 3) Vivaldi is a true alternative against that sea of endless uniform browsers with almost no differences.

There are other arguments too, of course. I just wanted to point out that there could be good reasons to include Vivaldi :)

**Comment by hareesh-pillai** [comment]
As of May 2020, the market share of Vivaldi is at 0.02%.

Source: [StatCounter](https://gs.statcounter.com/browser-market-share/desktop/chart.php?bar=1&device=Desktop&device_hidden=desktop&statType_hidden=browser&region_hidden=ww&granularity=monthly&statType=Browser&region=Worldwide&fromInt=202005&toInt=202005&fromMonthYear=2020-05&toMonthYear=2020-05&csv=1)

**Comment by Cqoicebordel** [comment]
1. Statcounter isn't representative anymore, as Vivaldi changed its UA to use the same as Chrome, for compatibility reasons. So Statcounter can't count anymore. Source : https://vivaldi.com/fr/blog/user-agent-changes/  
2. Right now, Vivaldi has 1.5+ millions users. And that doesn't count the mobile users. Source : https://vivaldi.com/company/

**Pull request closed without merging**
