### PR TITLE
Add zh_TW translation.

### PR DESCRIPTION
**Pull request by s8321414**
I add zh_TW locale here, can you merge it?

### CODE REVIEW

**Comment by s8321414** [comment]
So can we translate via GitHub or we should contribute to that website?

**Comment by s8321414** [comment]
......

**Comment by coffee2code** [comment]
Belated thanks for the contribution! As indicated in the README, localized translations of the site can be contributed via the GlotPress installation at https://translate.wordpress.org/projects/meta/browsehappy. Instructions are provided at the link.

As of this moment (and perhaps since your request), there exists translations for zh_TW. It's at 96% (only 1 string is missing translation). That is bound to change soon as a number of string will likely get changed.

Cheers!

**Comment by s8321414** [comment]
OK thanks.

**Pull request closed without merging**
