### PR TITLE
Add Brave browser

### PR DESCRIPTION
**Pull request by renintw**
Trac ticket: https://meta.trac.wordpress.org/ticket/6845

## Screencast
https://user-images.githubusercontent.com/18050944/225744588-d844c35f-1b16-40c6-b459-dba80ba3b869.mp4

### CODE REVIEW

**Comment by coffee2code** [comment]
Hi @renintw! Thanks for the PR. Since it looks like you might've already done it locally, could you include the updated `browsehappy-sprite-2x.png` and `browsehappy-sprite.png` images that include the Brave logo? If not and it was only a mockup for the demo video, that's not a problem and I can update them myself.

**Comment by renintw** [comment]
Hi @coffee2code! I've updated the sprites. Since I spent some time figuring out how others edit sprites, and I couldn't find out any guide or PRs explaining it so I just calculated a new logo width through the original sprites and used the sketch to add it, I'm wondering if this is the same/right way you edited the sprites?

**Comment by coffee2code** [comment]
@renintw: That's a perfectly fine way to update the sprite. There isn't much in the way of docs since new logos are rarely added or updated, but documentation is still warranted. Generally, I obtain the 256x256 version of the logo (for use in the 2x sprite; 128x128 for the 1x sprite) from [this repo](https://github.com/alrra/browser-logos/), then edit the existing sprite to replace an existing logo or extend the canvas to add a new logo. Which you've done. (However, that repo's version of the Brave logo appears a bit more orange-ish and less red to me than the actual logo and the logo you've used.)

Anyhow, the PR looks great, though there needs to be one more CSS tweak. In style.css on line 693 of your changed version (it's the very last CSS rule in the file), the background size needs adjusting:

```diff
- background-size: 750px 170px;
+ background-size: 875px 170px;
```

Happy to merge and deploy after that.

**Comment by renintw** [comment]
@coffee2code thanks for the clarification. I think if anyone else wants to try adding a new browser logo in the future, they can at least refer to your comment 🙂  I've adjusted the CSS as mentioned. Could you please do the merging and deploying for me? Thanks a bunch!

**Comment by renintw** [comment]
@coffee2code thanks for the clarification. I think if anyone else wants to try adding a new browser logo in the future, they can at least refer to the comment here 🙂  I've adjusted the CSS as mentioned. Could you please do the merging and deploying for me? Thanks a bunch!

**Pull request merged**
